void foo0();
void foo0(int);
void foo0(int, bool);
void foo0(int, d);
void foo0(int, d);
void foo0(int, d, a::b::c<d>::q);
void foo0(int x, d, a::b::c<d>::q);
void foo0(int x, d y, a::b::c<d>::q);
void foo0(int x, d y, a::b::c<d>::q z);
void foo0(int, d y, a::b::c<d>::q);
void foo0(int, d y, a::b::c<bool>::q z);
void foo0(int x, d, a::b::c<std::string>::q z);
void foo0(int x, d, a::b::c<a::b::c<std::string>::q>::q z = "apa");
void foo0(int x, d y = t, a::b::c<int>::q z = t1);
void foo1();
int foo1(int);
void foo1(int, const bool);
void foo1(int, const d &);
void foo1(int, d);
void foo1(int, const d, a::b::c<d>::q &);
void foo1(int x, d &, a::b::c<d>::q);
void foo1(int x, const d & y, a::b::c<d>::q);
void foo1(int x, d y, a::b::c<d>::q z);
void foo1(const int, d y, a::b::c<d>::q);
void foo1(int, d & y, a::b::c<bool>::q & z);
void foo1(int x, d, a::b::c<std::string>::q z);
void foo1(int x, d, const a::b::c<a::b::c<std::string>::q>::q z = "apa");
int foo1(int x, d & y = t, const a::b::c<int>::q & z = t1);
