package MiniJS.Absyn; // Java Package generated by the BNF Converter.

public class SPrint  extends Stm {
  public final Exp exp_;
  public SPrint(Exp p1) { exp_ = p1; }

  public <R,A> R accept(MiniJS.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof MiniJS.Absyn.SPrint) {
      MiniJS.Absyn.SPrint x = (MiniJS.Absyn.SPrint)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
