package MiniJS.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stm implements java.io.Serializable {
  public abstract <R,A> R accept(Stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(MiniJS.Absyn.SAssign p, A arg);
    public R visit(MiniJS.Absyn.SPrint p, A arg);

  }

}
