
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package MiniJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_8 = 10;
  public static final int _SYMB_7 = 9;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int EOF = 0;
  public static final int _IDENT_ = 13;
  public static final int error = 1;
  public static final int _INTEGER_ = 11;
  public static final int _DOUBLE_ = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "_SYMB_0",
  "_SYMB_1",
  "_SYMB_2",
  "_SYMB_3",
  "_SYMB_4",
  "_SYMB_5",
  "_SYMB_6",
  "_SYMB_7",
  "_SYMB_8",
  "_INTEGER_",
  "_DOUBLE_",
  "_IDENT_"
  };
}

