package Code.Absyn; // Java Package generated by the BNF Converter.

public class DLit  extends Ins {
  public final Double double_;
  public DLit(Double p1) { double_ = p1; }

  public <R,A> R accept(Code.Absyn.Ins.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Code.Absyn.DLit) {
      Code.Absyn.DLit x = (Code.Absyn.DLit)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
