package Ann.Absyn; // Java Package generated by the BNF Converter.

public class EI2D  extends Exp {
  public final Exp exp_;
  public EI2D(Exp p1) { exp_ = p1; }

  public <R,A> R accept(Ann.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Ann.Absyn.EI2D) {
      Ann.Absyn.EI2D x = (Ann.Absyn.EI2D)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
