package Ann.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Ann.Absyn.EInt p, A arg);
    public R visit(Ann.Absyn.EDouble p, A arg);
    public R visit(Ann.Absyn.EVar p, A arg);
    public R visit(Ann.Absyn.EArith p, A arg);
    public R visit(Ann.Absyn.EI2D p, A arg);

  }

}
