package Ann.Absyn; // Java Package generated by the BNF Converter.

public abstract class Op implements java.io.Serializable {
  public abstract <R,A> R accept(Op.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Ann.Absyn.Times p, A arg);
    public R visit(Ann.Absyn.Div p, A arg);
    public R visit(Ann.Absyn.Plus p, A arg);
    public R visit(Ann.Absyn.Minus p, A arg);

  }

}
