package Ann.Absyn; // Java Package generated by the BNF Converter.

public class EArith  extends Exp {
  public final Type type_;
  public final Exp exp_1, exp_2;
  public final Op op_;
  public EArith(Type p1, Exp p2, Op p3, Exp p4) { type_ = p1; exp_1 = p2; op_ = p3; exp_2 = p4; }

  public <R,A> R accept(Ann.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Ann.Absyn.EArith) {
      Ann.Absyn.EArith x = (Ann.Absyn.EArith)o;
      return this.type_.equals(x.type_) && this.exp_1.equals(x.exp_1) && this.op_.equals(x.op_) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.type_.hashCode())+this.exp_1.hashCode())+this.op_.hashCode())+this.exp_2.hashCode();
  }


}
