package Ann.Absyn; // Java Package generated by the BNF Converter.

public class SAssign  extends Stm {
  public final String ident_;
  public final Type type_;
  public final Exp exp_;
  public SAssign(String p1, Type p2, Exp p3) { ident_ = p1; type_ = p2; exp_ = p3; }

  public <R,A> R accept(Ann.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Ann.Absyn.SAssign) {
      Ann.Absyn.SAssign x = (Ann.Absyn.SAssign)o;
      return this.ident_.equals(x.ident_) && this.type_.equals(x.type_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.type_.hashCode())+this.exp_.hashCode();
  }


}
