package Ann.Absyn; // Java Package generated by the BNF Converter.

public class TDouble  extends Type {
  public TDouble() { }

  public <R,A> R accept(Ann.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Ann.Absyn.TDouble) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
