package Code.Absyn; // Java Package generated by the BNF Converter.

public abstract class Ins implements java.io.Serializable {
  public abstract <R,A> R accept(Ins.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Code.Absyn.ILoad p, A arg);
    public R visit(Code.Absyn.IStore p, A arg);
    public R visit(Code.Absyn.IAdd p, A arg);
    public R visit(Code.Absyn.ISub p, A arg);
    public R visit(Code.Absyn.IMul p, A arg);
    public R visit(Code.Absyn.IDiv p, A arg);
    public R visit(Code.Absyn.ILit p, A arg);
    public R visit(Code.Absyn.DLoad p, A arg);
    public R visit(Code.Absyn.DStore p, A arg);
    public R visit(Code.Absyn.DAdd p, A arg);
    public R visit(Code.Absyn.DSub p, A arg);
    public R visit(Code.Absyn.DMul p, A arg);
    public R visit(Code.Absyn.DDiv p, A arg);
    public R visit(Code.Absyn.DLit p, A arg);
    public R visit(Code.Absyn.I2D p, A arg);
    public R visit(Code.Absyn.IPrint p, A arg);
    public R visit(Code.Absyn.DPrint p, A arg);

  }

}
