name: Deploy PLT www

on:
  push:         { branches: [ master, ci-* ] }
  pull_request: { branches: [ master, ci-* ] }
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install pandoc
      run: |
        sudo apt install pandoc

    - name: Set up Python 2
      uses: actions/setup-python@v4
      with:
        python-version: ${{ '2.7' }}

    - name: Info about the Python setup
      run: |
        python --version
        python2 --version

    - name: Local PATH
      run: |
        mkdir -p "${HOME}/.local/bin"
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"

    - name: Install txt2tags
      run: |
        wget https://github.com/txt2tags/old/raw/master/txt2tags-2.6.tgz
        tar xf txt2tags-2.6.tgz
        mv txt2tags-2.6/txt2tags "${HOME}/.local/bin/"
        chmod +x "${HOME}/.local/bin/txt2tags"
        txt2tags --version
      # not needed: we change the first line to '#!/usr/bin/env python2' by appending a 2
      # sed -i '2s/$/2/' ~/.local/bin/txt2tags

    - name: Install BNFC
      run: |
        wget https://github.com/BNFC/bnfc/releases/download/v2.9.4.1/bnfc-2.9.4.1-linux.binary
        mv bnfc-2.9.4.1-linux.binary "${HOME}/.local/bin/bnfc"
        chmod +x "${HOME}/.local/bin/bnfc"

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v2
      with:
        packages: >-
          scheme-basic
          graphics
          hyperref
          lkproof
          paralist
          ulem
          xcolor

        # plain

    - uses: actions/checkout@v3

    - run: make
